CampusFleaMarket/CampusFleaMarket.UI/Controllers/BackManager/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CampusFleaMarket.UI.Controllers.BackManager
{
    using IBLL;
    using Model;
    using FactoryBLL;
    using System.IO;
    public class UserManagerController :Controller
    {
        
        public IUserService services
        {
            get { return FactoryService.GetCurrentBLLContext().UserService; }
        }
        //
        // GET: /UserManager/

        public ActionResult Index(int currentPage=1, int dataCount = 10)
        {
            ViewData.Model = services.GetAllEntity(u => u.U_StuNumber).Skip((currentPage - 1) * dataCount).Take(dataCount);
            ViewBag.total = (services.GetAllEntity().Count+ dataCount)/dataCount;
            return View();
        }

        #region 0.0 新增+Create
       
        [HttpGet]
        /// <summary>
        /// 返回新增用户模态窗口需要的数据
        /// </summary>
        /// <returns></returns>
        public ActionResult PartialCreate()
        {

            ViewBag.U_State = new SelectList(new Models.U_StateDataSource().dataSource, "Id", "U_State");
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(Users user)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    
                    //1.0将学生证保存到服务器上
                    if (user.CompusCard != null)
                    {
                        foreach (var item in user.CompusCard)
                        {
                            string CGUID1 = System.Guid.NewGuid().ToString() + ".jpg";
                            string CampuCardFilePath1 = Server.MapPath(string.Format("~/Image/CampusCard/{0}", CGUID1));
                            item.SaveAs(Path.Combine(CampuCardFilePath1));
                            user.U_CompusCard += CGUID1.ToString()+";";
                        }
                    }
                    else {
                        throw new Exception("未上传学生证");
                    }
                    //2.0将头像保存到服务上
                    if (user.Head_Image != null)
                    {
                        string HGUID1 = System.Guid.NewGuid().ToString() + "jpg";
                        string HeadImgFilePath = Server.MapPath(string.Format("~/Image/HeadImage/{0}", HGUID1));
                        user.Head_Image.SaveAs(Path.Combine(HeadImgFilePath));
                        user.U_HeadImage = HGUID1;

                    }
                    else {
                        user.U_HeadImage = "1.jpg";//添加默认头像
                    }
                    services.AddEntity(user);
                }
                catch(Exception ex) {
                    Response.Write("<script>alert('"+ex.Message+"')</script>");
                }
            }
            return RedirectToAction("Index");
        }
        #endregion


        #region  1.0 修改+Edit
        [HttpGet]
        public ActionResult PartialEdit(int id)
        {

            Users user = services.GetEntityByLambada(u => u.U_ID == id);
                        ViewBag.U_State = new SelectList(new Models.U_StateDataSource().dataSource, "Id", "U_State",user.U_State);
            ViewData.Model = user;
            return PartialView();
        }


        [HttpPost]
        public ActionResult Edit(Users users)
        {
            
            if (ModelState.IsValid)
            {
                this.services.UpdateEntity(users);
            }

            return View();
        }
        
        #endregion

        #region 2.0 删除+Delete

        [HttpGet]
        public ActionResult PartialDelete(int id)
        {
            Users user = services.GetEntityByLambada(u => u.U_ID == id);
            ViewBag.id = id;
            ViewBag.U_Name = user.U_Name;
            return PartialView();
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            Users user = services.GetEntityByLambada(u => u.U_ID == id);
            services.DeleteEntity(user);
            return RedirectToAction("index");
        }

        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="select"></param>
        /// <returns></returns>
        public ActionResult AllDelete(string[] select)
        {
            services.DeleteEntitys(select);
            return RedirectToAction("Index");

        }
        #endregion

        #region 3.0 详细+Detail
        public ActionResult PartialDetail(int id)
        {
           Users user = services.GetEntityByLambada(u => u.U_ID == id);
           ViewData.Model = user;
           ViewBag.id = id;
           ViewBag.Campuscard  = user.U_CompusCard.Split(';');
            return PartialView();
        }
        #endregion
        
    }
}

CampusFleaMarket/CampusFleaMarket.UI/Views/UserManager/Create.cshtml
@model CampusFleaMarket.Model.Users

@{
    Layout = "~/Views/Shared/Manager_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>
        .o_container {
            width:200px;
            margin:0 auto;
        }
    </style>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm("Create", "UserManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>填写信息</legend>
   
            <div class="o_container">

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_StuNumber)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_StuNumber)
                    @Html.ValidationMessageFor(model => model.U_StuNumber)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Name)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Name)
                    @Html.ValidationMessageFor(model => model.U_Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Passward)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Passward)
                    @Html.ValidationMessageFor(model => model.U_Passward)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Phone)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Phone)
                    @Html.ValidationMessageFor(model => model.U_Phone)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Head_Image)
                </div>
                <div class="editor-field">
                    <input type="file" accept="image/png,image/gif,image/jpg,image/jpeg" name="Head_Image" />
                    @Html.ValidationMessageFor(model => model.U_HeadImage)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.CompusCard)
                </div>
                <div class="editor-field">
                    <input type="file" multiple accept="image/png,image/gif,image/jpg,image/jpeg" name="CompusCard" />
                    @Html.ValidationMessageFor(model => model.CompusCard)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_State)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_State)
                    @Html.ValidationMessageFor(model => model.U_State)
                </div>

                <p>
                    <input type="submit" value="Create" />
                </p>

            </div>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("返回列表", "Index")
    </div>
</body>
</html>

CampusFleaMarket/CampusFleaMarket.UI/Views/UserManager/Delete.cshtml
@model CampusFleaMarket.Model.Users

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Users</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.U_ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.U_ID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.U_StuNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.U_StuNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.U_Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.U_Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.U_Passward)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.U_Passward)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.U_Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.U_Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.U_State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.U_State)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CampusFleaMarket/CampusFleaMarket.UI/Views/UserManager/Index.cshtml
@model IEnumerable<CampusFleaMarket.Model.Users>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Manager_Layout.cshtml";
}

@section styles{

    <style>
        .d_td {
            width: 100%;
            white-space: nowrap;
            text-overflow: ellipsis;
            overflow: hidden;
            padding: 10px 10px;
        }
    </style>


}
<h3>注册用户列表</h3>
<button type="button" id="Create" data-toggle="modal" data-target="#modal-dialog" class="btn btn-default">添加</button>
<button type="button" id="AllDelte" class="btn btn-default">批量删除</button>
@using (Html.BeginForm("AllDelete", "UserManager", FormMethod.Post, new { id = "AllDeleteForm" }))
{

    <table id="showTable" border="1" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td>
                <input type="checkbox" id="checkAll" />全选
            </td>
            <th>
                @Html.DisplayNameFor(model => model.U_StuNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.U_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.U_Passward)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.U_Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.U_State)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td width="5%">
                    <input type="checkbox" name="select" value="@item.U_ID" />
                </td>
                <td width="10%">
                    <div class="d_td">  @Html.DisplayFor(modelItem => item.U_StuNumber)</div>
                </td>
                <td width="20%">
                    <div class="d_td"> @Html.DisplayFor(modelItem => item.U_Name)</div>
                </td>
                <td>
                    <div class="d_td"> @Html.DisplayFor(modelItem => item.U_Passward)</div>
                </td>
                <td width="15%">
                    <div class="d_td"> @Html.DisplayFor(modelItem => item.U_Phone)</div>
                </td>

                <td>
                    <div class="d_td"> @(item.U_State == "0" ? "未通过" : "已通过")</div>
                </td>
                <td width="150px">
                    <div class="d_td">
                        <button type="button" data-primaryid="@item.U_ID" data-toggle="modal" data-target="#modal-dialog" class="btn btn-default Edit">修改</button>  |
                        <button type="button" data-primaryid="@item.U_ID" data-toggle="modal" data-target="#modal-dialog" class="btn btn-default Detail">详细</button>  |
                        <button type="button" data-primaryid="@item.U_ID" data-toggle="modal" data-target="#modal-dialog" class="btn btn-default Delete">删除</button>  
                    </div>
                </td>
            </tr>
        }

    </table>
}

<ul class="pagination">
    <li><a href="#">&laquo;</a></li>
    @for (int i = 1; i <= ViewBag.total; i++)
    {
            
        <li>@Html.ActionLink(i.ToString(), "index", new { currentPage = i, dataCount = 10 })</li>
    }
    <li><a href="#">&raquo;</a></li>
</ul>





<!-- 模态框（Modal）2 -->
<div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id="modal-content" class="modal-content">


        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>





@section scripts{
    //菜单列设置样式
    $(".cfm-num2List li").eq(0).css("background-color", "#FCFCFC");


}
@Scripts.Render("~/Content/UserManagerJs")

CampusFleaMarket/CampusFleaMarket.UI/Views/UserManager/PartialCreate.cshtml
@model CampusFleaMarket.Model.Users

<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("Create", "UserManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
        </button>
        <h4 class="modal-title" id="myModalLabel">
            创建用户
        </h4>
    </div>

    <div class="modal-body">
        <fieldset>
            <legend>【填写信息】</legend>

            <div class="o_container">

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_StuNumber)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_StuNumber)
                    @Html.ValidationMessageFor(model => model.U_StuNumber)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Name)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Name)
                    @Html.ValidationMessageFor(model => model.U_Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Passward)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Passward)
                    @Html.ValidationMessageFor(model => model.U_Passward)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Phone)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Phone)
                    @Html.ValidationMessageFor(model => model.U_Phone)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Head_Image)
                </div>
                <div class="editor-field">
                    <input type="file" accept="image/png,image/gif,image/jpg,image/jpeg" name="Head_Image" />
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.CompusCard)
                </div>
                <div class="editor-field">
                    <input type="file" multiple data-val="true" id="CompusCard" data-val-required="请上传你的校园卡" accept="image/png,image/gif,image/jpg,image/jpeg" name="CompusCard" />
                    @Html.ValidationMessageFor(model => model.CompusCard)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_State)
                </div>
                <div class="editor-field">

                    @Html.DropDownList("U_State");
                    @Html.ValidationMessageFor(model => model.U_State)
                </div>

            </div>
        </fieldset>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            关闭
        </button>
        <button type="submit" class="btn btn-primary">
            添加
        </button>
    </div>


}

CampusFleaMarket/CampusFleaMarket.UI/Views/UserManager/PartialDelete.cshtml
@model CampusFleaMarket.Model.Users
@using (Html.BeginForm("Delete","usermanager",FormMethod.Post)) {
    @Html.AntiForgeryToken()
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
        </button>
        <h4 class="modal-title" id="myModalLabel">
        </h4>
    </div>

    <div class="modal-body">
        @Html.Hidden("id",(int)ViewBag.id)
        <h3>你确定要删除【@(ViewBag.U_Name)】该用户吗？</h3>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            关闭
        </button>
        <button type="submit" class="btn btn-primary">
            删除
        </button>
    </div>
}

CampusFleaMarket/CampusFleaMarket.UI/Views/UserManager/PartialDetail.cshtml
@model CampusFleaMarket.Model.Users
<style>
    tr {
        background:black;
    }
 </style>
<div id="modal-content2">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
        </button>
        <h4 class="modal-title" id="myModalLabel"></h4>
    </div>

    <div class="modal-body">


        <fieldset>
            <legend>详细信息</legend>
            <table border="1" width="100%" align="center">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.U_StuNumber)</th>
                    <td colspan="2">@Html.DisplayFor(model => model.U_StuNumber)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.U_Name)</th>
                    <td colspan="2">@Html.DisplayFor(model => model.U_Name)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.U_Passward)</th>
                    <td colspan="2">@Html.DisplayFor(model => model.U_Passward)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.CompusCard)</th>
                    <td><img width="100px" src="/Image/CampusCard/@(ViewBag.Campuscard[0])" alt="图片不存在" /></td>
                    <td>
                        <img width="100px" src="/Image/CampusCard/@(ViewBag.Campuscard[1])" alt="图片不存在" />
                    </td>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Head_Image)</th>
                    <td colspan="2">@Html.DisplayFor(model => model.U_StuNumber)</td>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.U_StuNumber)</th>
                    <td colspan="2">@Html.DisplayFor(model => model.U_StuNumber)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.U_State)</th>
                    <td colspan="2">@(Model.U_State == "0" ? "未通过" : "已通过")</td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            关闭
        </button>
        <button type="submit" data-primaryid="@((int)ViewBag.id)" class="btn btn-primary Edit">
            编辑
        </button>
    </div>
</div>
@*@Scripts.Render("~/bundles/jquery")*@
<script>

    $(document).ready(function () {

        //编辑按钮点击跳弹框
        $(".Edit").click(function () {
            //alert("ajax请求修改部分视图")
            var primaryId = $(this).data("primaryid");
            //alert(primaryId)
            $("#modal-content2").load("UserManager/PartialEdit", "id=" + primaryId, function (req, sta, xhr) {
                //var a = document.getElementById("modal-content");
                //a.innerText = req
                //alert(req)
            })

        })


    })

</script>

CampusFleaMarket/CampusFleaMarket.UI/Views/UserManager/PartialEdit.cshtml
@model CampusFleaMarket.Model.Users


<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("Create", "UserManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
        </button>
        <h4 class="modal-title" id="myModalLabel">
            修改用户
        </h4>
    </div>

    <div class="modal-body">
        <fieldset>
            <legend>【修改信息】</legend>

            <div class="o_container">

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_StuNumber)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_StuNumber)
                    @Html.ValidationMessageFor(model => model.U_StuNumber)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Name)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Name)
                    @Html.ValidationMessageFor(model => model.U_Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Passward)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Passward)
                    @Html.ValidationMessageFor(model => model.U_Passward)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.U_Phone)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.U_Phone)
                    @Html.ValidationMessageFor(model => model.U_Phone)
                </div>


                <div class="editor-label">
                    @Html.LabelFor(model => model.U_State)
                </div>
                
                <div class="editor-field">
                    @Html.DropDownList("U_State")
                    @Html.ValidationMessageFor(model => model.U_State)
                </div>

            </div>
        </fieldset>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            关闭
        </button>
        <button type="submit" class="btn btn-primary">
            修改
        </button>
    </div>
}