CampusFleaMarket/CampusFleaMarket.UI/Controllers/BackManager/GoodManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CampusFleaMarket.UI.Controllers.BackManager
{
    using Model;
    using IBLL;
    using FactoryBLL;
    public class GoodManagerController : Controller,IBaseController<IGoodsService>
    {
        //
        // GET: /GoodManager/

        public IGoodsService services
        {

            get { return FactoryService.GetCurrentBLLContext().GoodsService; }
        }
        public ActionResult Index()
        {
            ViewData.Model = services.GetAllEntity();
            return View();
        }
        #region 1.0 新增二手物品
        [HttpGet]
        public ActionResult Create()
        {

            ViewBag.G_Category = new SelectList(services.GetCategoryOfGoods, "C_ID", "C_Name");
            ViewBag.G_User = new SelectList(services.GetUsers, "U_ID", "U_Name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Goods good)
        {
            services.AddEntity(good);
            return RedirectToAction("Index");
        
        }
        #endregion
        #region 2.0 修改二手物品信息
        public ActionResult Edit(int id)
        {
            return null;
        }
        #endregion

        #region 3.0 删除二手物品信息
        public ActionResult Delete(int id)
        {
            Goods G = services.GetEntityByLambada(s=>s.G_ID == id);
            services.DeleteEntity(G);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="select"></param>
        /// <returns></returns>
        public ActionResult AllDelete(string[] select)
        {
            services.DeleteEntitys(select);
            return RedirectToAction("Index");
        }

        #endregion


        #region 4.0 二手物品详细信息
        public ActionResult Detail(int id)
        {

            return null;
        }
        #endregion




        public ActionResult GetUsersByFenYe(int currentPage, int dataCount)
        {
            throw new NotImplementedException();
        }
    }
}

CampusFleaMarket/CampusFleaMarket.UI/Views/GoodManager/Create.cshtml
@model CampusFleaMarket.Model.Goods

@{
    ViewBag.Title = "Create";
}

<h2>添加</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>二手物品信息</legend>


        <div class="editor-label">
            二手物品名称
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.G_Name)
            @Html.ValidationMessageFor(model => model.G_Name)
        </div>

        <div class="editor-label">
            类别
        </div>
        <div class="editor-field">
            @Html.DropDownList("G_Category")
            @Html.ValidationMessageFor(model => model.CategoryOfGoods)
        </div>

        <div class="editor-label">
          描述
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.G_Description)
            @Html.ValidationMessageFor(model => model.G_Description)
        </div>

        <div class="editor-label">
           发布者
        </div>
        <div class="editor-field">
            @Html.DropDownList("G_User")
            @Html.ValidationMessageFor(model => model.G_User)
        </div>

        <div class="editor-label">
            价格
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.G_Price)
            @Html.ValidationMessageFor(model => model.G_Price)
        </div>

        <div class="editor-label">
            库存
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.G_Inventory)
            @Html.ValidationMessageFor(model => model.G_Inventory)
        </div>


        <div class="editor-label">
            审核状态
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.G_State)
            @Html.ValidationMessageFor(model => model.G_State)
        </div>

        <p>
            <input type="submit" value="添加" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("返回二手物品列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CampusFleaMarket/CampusFleaMarket.UI/Views/GoodManager/Index.cshtml
@model IEnumerable<CampusFleaMarket.Model.Goods>

@{
    ViewBag.Title = "商品管理";
    Layout = "~/Views/Shared/Manager_Layout.cshtml";
}
@section Style{
    <style>



    </style>
}
@section Script{
    <script>
        function confirmDelete(name, id) {
            var result = confirm("你确定要删除【" + name + "】吗？");
            if (result) {

                window.location = "@(Url.Action("Delete"))/" + id
            }
        }

        function comfirmAllDelete() {
            if (confirm("你确定要批量删除吗？")) {
                window.document.getElementsByTagName("form")[0].submit();
            }
        }
    </script>

}
<h2>二手物品列表</h2>
@section Create{
    @Html.ActionLink("添加", "Create")
    <a href="#" onclick="comfirmAllDelete()">批量删除</a>
}
@using (Html.BeginForm("AllDelete", "GoodManager"))
{
    <table border="1" cellspacing="0">
        <tr bgcolor="#757675" style="color: white">
            <th>
                <input type="checkbox" id="allSelect" />
                全选
            </th>
            <th>
                物品名称
            </th>
            <th>
                类别
            </th>
            <th>
                描述
            </th>
            <th>
                发布用户
            </th>
            <th>
                价格
            </th>
            <th>
                发表日期
            </th>
            <th>
                商品状态
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
{
    <tr>
        <td>
            <div class="d_tr"><input type="checkbox" name="select" value="@item.G_ID" /></div>
        </td>
        <td>
            <div class="d_tr">@Html.DisplayFor(modelItem => item.G_Name)</div>
        </td>
        <td>
            <div class="d_tr">@Html.DisplayFor(modelItem => item.CategoryOfGoods.C_Name)</div>
        </td>
        <td>
            <div class="d_tr">@Html.DisplayFor(modelItem => item.G_Description)</div>
        </td>
        <td>
            <div class="d_tr">@Html.DisplayFor(modelItem => item.Users.U_Name)</div>
        </td>
        <td>
            <div class="d_tr">@Html.DisplayFor(modelItem => item.G_Price)</div>
        </td>
        <td>
            <div class="d_tr">@Html.DisplayFor(modelItem => item.G_Date)</div>
        </td>
        <td>
            <div class="d_tr">@Html.DisplayFor(modelItem => item.G_State)</div>
        </td>
        <td>
            @Html.ActionLink("修改", "Edit", new {  id=item.G_ID }) |
            @Html.ActionLink("详细", "Details", new {  id=item.G_ID }) |
            <a href="#" onclick="confirmDelete(' @(item.G_Name)',@(item.G_ID))">删除</a>
        </td>
    </tr>
}

    </table>
}